// <auto-generated />
using System;
using Infrastructure.Concrete;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Infrastructure.Migrations
{
    [DbContext(typeof(Context))]
    [Migration("20221002091302_receiveddatenullable")]
    partial class receiveddatenullable
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Entity.Concrete.Message", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnOrder(1)
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("varchar")
                        .HasColumnOrder(13);

                    b.Property<decimal>("CreatedDate")
                        .HasColumnType("numeric")
                        .HasColumnOrder(11);

                    b.Property<decimal>("CreatedTime")
                        .HasColumnType("numeric")
                        .HasColumnOrder(12);

                    b.Property<Guid>("FromId")
                        .HasColumnType("uuid")
                        .HasColumnOrder(8);

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean")
                        .HasColumnOrder(10);

                    b.Property<decimal>("MessageStatus")
                        .HasPrecision(8)
                        .HasColumnType("numeric(8)")
                        .HasColumnOrder(3);

                    b.Property<decimal?>("ReceivedDate")
                        .HasColumnType("numeric")
                        .HasColumnOrder(6);

                    b.Property<decimal?>("ReceivedTime")
                        .HasColumnType("numeric")
                        .HasColumnOrder(7);

                    b.Property<decimal>("SendDate")
                        .HasColumnType("numeric")
                        .HasColumnOrder(4);

                    b.Property<decimal>("SendTime")
                        .HasColumnType("numeric")
                        .HasColumnOrder(5);

                    b.Property<string>("Text")
                        .HasMaxLength(4000)
                        .HasColumnType("text")
                        .HasColumnOrder(2);

                    b.Property<Guid>("ToId")
                        .HasColumnType("uuid")
                        .HasColumnOrder(9);

                    b.Property<string>("UpdatedBy")
                        .HasColumnType("varchar")
                        .HasColumnOrder(16);

                    b.Property<decimal?>("UpdatedDate")
                        .HasColumnType("numeric")
                        .HasColumnOrder(14);

                    b.Property<decimal?>("UpdatedTime")
                        .HasColumnType("numeric")
                        .HasColumnOrder(15);

                    b.HasKey("Id");

                    b.HasIndex("FromId");

                    b.HasIndex("ToId");

                    b.ToTable("Message");
                });

            modelBuilder.Entity("Entity.Concrete.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnOrder(1)
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<decimal>("BirthDate")
                        .HasPrecision(8)
                        .HasColumnType("numeric(8)")
                        .HasColumnOrder(6);

                    b.Property<string>("CreatedBy")
                        .HasColumnType("varchar")
                        .HasColumnOrder(10);

                    b.Property<decimal>("CreatedDate")
                        .HasColumnType("numeric")
                        .HasColumnOrder(8);

                    b.Property<decimal>("CreatedTime")
                        .HasColumnType("numeric")
                        .HasColumnOrder(9);

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean")
                        .HasColumnOrder(7);

                    b.Property<string>("MobilePhone")
                        .IsRequired()
                        .HasColumnType("varchar")
                        .HasColumnOrder(5);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar")
                        .HasColumnOrder(2);

                    b.Property<string>("Surname")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar")
                        .HasColumnOrder(3);

                    b.Property<string>("UpdatedBy")
                        .HasColumnType("varchar")
                        .HasColumnOrder(13);

                    b.Property<decimal?>("UpdatedDate")
                        .HasColumnType("numeric")
                        .HasColumnOrder(11);

                    b.Property<decimal?>("UpdatedTime")
                        .HasColumnType("numeric")
                        .HasColumnOrder(12);

                    b.Property<string>("UserName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar")
                        .HasColumnOrder(4);

                    b.HasKey("Id");

                    b.HasIndex("MobilePhone");

                    b.ToTable("User");
                });

            modelBuilder.Entity("Entity.Concrete.Message", b =>
                {
                    b.HasOne("Entity.Concrete.User", "FromUser")
                        .WithMany("FromMessages")
                        .HasForeignKey("FromId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Entity.Concrete.User", "ToUser")
                        .WithMany("ToMessages")
                        .HasForeignKey("ToId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("FromUser");

                    b.Navigation("ToUser");
                });

            modelBuilder.Entity("Entity.Concrete.User", b =>
                {
                    b.Navigation("FromMessages");

                    b.Navigation("ToMessages");
                });
#pragma warning restore 612, 618
        }
    }
}
